### ISSUE TITLE
Request to add license

### ISSUE THREAD

**Issue by ArkaneMoose** [erichlotto/Play-Music-Lyrics-Fetcher#20]
Currently your repository has no license, which, as explained on the [GitHub's Choose a License site](https://choosealicense.com/no-license/), means that your work is under exclusive copyright by default. I'd like to fork and make improvements to the code, but before I do, I'd prefer that you add an open-source license first.

The aforementioned [Choose a License site](https://choosealicense.com/) can help you pick the open-source license you feel is most appropriate for this project.

Thanks!

**Comment by erichlotto** [comment]
There you go, the source is now under GNU GPLv3. Thanks for the heads up :)
