### ISSUE TITLE
External Window Resizes Itself

### ISSUE THREAD

**Issue by jou-calvin** [erichlotto/Play-Music-Lyrics-Fetcher#24]
When a song changes, the external window resizes itself to the default. Is it possible for the window to maintain its size between songs?

![image](https://user-images.githubusercontent.com/9372665/30355150-105feba4-97f7-11e7-9d79-3061509876ef.png)

**Comment by erichlotto** [comment]
The window resizes itself to display the lyrics properly, this is by design.
Added an option to disabled this feature in v1.0.12 :+1:
